stages:
  - build
  - test
  - analyze
  - package
  - deploy

image: maven:3.9.7-eclipse-temurin-21

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"
  SONAR_HOST_URL: "http://sonarqube:9000"
  SONAR_TOKEN: "sqa_f8596ae9c344d01536b73ba1c56a082de51cb709"
  SONAR_PROJECT_KEY: "ConnectFour"

build:
  stage: build
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
      - "target/*"
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn compile

test:
  stage: test
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  dependencies:
    - build
  script:
    - mvn test

analyze:
  stage: analyze
  tags:
      - docker
  cache:
    paths:
      - $maven_packages_cache
  dependencies:
      - build
      - test
  allow_failure: true
  artifacts:
    expire_in: 1 week
    paths:
      - "target/surefire-report/*"
      - "target/site/jacoco/*"
  script:
      - mvn sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN -Dsonar.exclusions="**/*.css,**/*.css.map,**/*.js,**/*.js.map"

package:
  stage: package
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  dependencies:
    - build
  artifacts:
    paths:
      - target/*.war
  script:
    - mvn package

deploy_test:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  when: manual
  environment:
    name: test
    action: start
    url: http://localhost:8081/ConnectFour
    on_stop: stop_test
  script:
    - docker rm --force tomcat
    - docker image rm --force connect-four
    - docker build -t connect-four .
    - docker run --rm -d --name tomcat -p 8081:8080 connect-four

stop_test:
  stage: deploy
  tags:
    - shell
  when: manual
  environment:
    name: test
    action: stop
  script:
    - docker rm --force tomcat
    - docker image rm --force connect-four